version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
      - db
      - redis
    ports:
      - "3000:3000" # Backend NestJS
      - "5173:5173" # UI Vite

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_database
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"